<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-GSManager.Mailer-eb39d8ba-918b-46b2-a515-23c7a1729c0c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.1.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\GSManager.Contracts\GSManager.Contracts.csproj" />
    <ProjectReference Include="..\..\AspireServiceDefaults\AspireServiceDefaults.csproj" />
  </ItemGroup>
</Project>
