using FluentValidation;
using GSManager.API.ExceptionHandlers;
using GSManager.API.JsonConverters;
using GSManager.API.Telemetry;
using GSManager.Core.Options;
using GSManager.Infrastructure.SQL.Options;
using Microsoft.AspNetCore.Mvc;

namespace GSManager.API.Config;

/// <summary>
/// Configures dependency injection for the API layer.
/// </summary>
public static class DependencyInjection
{
    public static IServiceCollection AddApiServices(this IServiceCollection services, IConfiguration configuration)
    {
        services.AddOptionsConfiguration(configuration);
        services.AddControllersConfiguration();
        services.AddCorsConfiguration();
        services.AddValidatorsConfiguration();
        services.AddExceptionHandlersConfiguration();
        services.AddTelemetryConfiguration();

        return services;
    }

    private static void AddOptionsConfiguration(this IServiceCollection services, IConfiguration configuration)
    {
        services.Configure<DatabaseOptions>(configuration.GetSection("SqlServerDatabase"));
        services.Configure<JwtOptions>(configuration.GetSection("Jwt"));
    }

    private static void AddControllersConfiguration(this IServiceCollection services)
    {
        services.AddHttpContextAccessor();
        services.AddControllers()
            .AddJsonOptions(options => options.JsonSerializerOptions.Converters.Add(new NullableGuidConverter()));
        services.AddOpenApi(options =>
        {
            options.AddDocumentTransformer((document, context, cancellationToken) =>
            {
                document.Info = new()
                {
                    Title = "GSManager API",
                    Version = "v1",
                    Description = "REST API for managing a garden society — members, plots, electricity meters, roles, and payments."
                };
                return Task.CompletedTask;
            });
            options.AddOperationTransformer((operation, context, cancellationToken) =>
            {
                foreach (var (code, response) in operation.Responses)
                {
                    response.Description = code switch
                    {
                        "200" => "Success",
                        "201" => "Created",
                        "204" => "No content",
                        "400" => "The request body or query parameters are invalid.",
                        "401" => "Authentication required — JWT bearer token is missing or invalid.",
                        "403" => "Access denied — you do not have the required permissions.",
                        "404" => "The requested resource was not found.",
                        _ => response.Description ?? string.Empty
                    };
                }
                return Task.CompletedTask;
            });
            options.AddSchemaTransformer((schema, context, cancellationToken) =>
            {
                if (context.JsonTypeInfo.Type != typeof(ProblemDetails))
                {
                    return Task.CompletedTask;
                }

                if (schema.Properties.TryGetValue("type", out var typeSchema))
                    typeSchema.Description = "A URI reference identifying the problem type. Set to the exception class name.";
                if (schema.Properties.TryGetValue("title", out var titleSchema))
                    titleSchema.Description = "A short, human-readable summary of the problem type.";
                if (schema.Properties.TryGetValue("status", out var statusSchema))
                    statusSchema.Description = "The HTTP status code generated by the server for this problem.";
                if (schema.Properties.TryGetValue("detail", out var detailSchema))
                    detailSchema.Description = "A human-readable explanation specific to this occurrence of the problem.";
                if (schema.Properties.TryGetValue("instance", out var instanceSchema))
                    instanceSchema.Description = "A URI reference identifying the specific occurrence of the problem.";

                return Task.CompletedTask;
            });
        });
    }

    private static void AddCorsConfiguration(this IServiceCollection services)
    {
        services.AddCors(options => options.AddDefaultPolicy(policy => policy
            .WithOrigins("http://localhost:4300")
            .AllowAnyHeader()
            .AllowAnyMethod()
            .AllowCredentials()));
    }

    private static void AddValidatorsConfiguration(this IServiceCollection services)
    {
        var assemblies = AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => a.FullName?.StartsWith("GSManager.Core,", StringComparison.OrdinalIgnoreCase) == true)
            .ToArray();
        services.AddValidatorsFromAssemblies(assemblies, includeInternalTypes: true);
    }

    private static void AddExceptionHandlersConfiguration(this IServiceCollection services)
    {
        services.AddExceptionHandler<GSManagerExceptionHandler>();
        services.AddExceptionHandler<DatabaseExceptionHandler>();
        services.AddExceptionHandler<GlobalExceptionHandler>();
        services.AddProblemDetails();
    }

    private static void AddTelemetryConfiguration(this IServiceCollection services)
    {
        services.AddSingleton<ApiMeters>();
    }
}
